#!/bin/bash
USER=$DG_FTP_USERNAME
PASSWORD=$DG_FTP_PASSWORD

echo "First build everything."
npm run build

echo "Entering dist directory."
cd dist

echo "Inventory..."
ls -l 

echo "Initiate ftp session."

ftp -n -v digitalgeyser.com <<EOF
quote USER $USER
quote PASS $PASSWORD
prompt
bin
put index.html
cd assets 
lcd assets 
mput *
quit
EOF
